//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from grammar/CPrep.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace QMKLib.Layout.CPrep {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="CPrepParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface ICPrepListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.defineOrEnd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDefineOrEnd([NotNull] CPrepParser.DefineOrEndContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.defineOrEnd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDefineOrEnd([NotNull] CPrepParser.DefineOrEndContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.end"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnd([NotNull] CPrepParser.EndContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.end"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnd([NotNull] CPrepParser.EndContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.defineDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDefineDeclaration([NotNull] CPrepParser.DefineDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.defineDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDefineDeclaration([NotNull] CPrepParser.DefineDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.defineSubst"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDefineSubst([NotNull] CPrepParser.DefineSubstContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.defineSubst"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDefineSubst([NotNull] CPrepParser.DefineSubstContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.layoutMacro"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLayoutMacro([NotNull] CPrepParser.LayoutMacroContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.layoutMacro"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLayoutMacro([NotNull] CPrepParser.LayoutMacroContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.layoutTargetRow"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLayoutTargetRow([NotNull] CPrepParser.LayoutTargetRowContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.layoutTargetRow"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLayoutTargetRow([NotNull] CPrepParser.LayoutTargetRowContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.layoutTarget"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLayoutTarget([NotNull] CPrepParser.LayoutTargetContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.layoutTarget"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLayoutTarget([NotNull] CPrepParser.LayoutTargetContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.layoutSource"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLayoutSource([NotNull] CPrepParser.LayoutSourceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.layoutSource"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLayoutSource([NotNull] CPrepParser.LayoutSourceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimaryExpression([NotNull] CPrepParser.PrimaryExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimaryExpression([NotNull] CPrepParser.PrimaryExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.genericSelection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGenericSelection([NotNull] CPrepParser.GenericSelectionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.genericSelection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGenericSelection([NotNull] CPrepParser.GenericSelectionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.genericAssocList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGenericAssocList([NotNull] CPrepParser.GenericAssocListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.genericAssocList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGenericAssocList([NotNull] CPrepParser.GenericAssocListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.genericAssociation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGenericAssociation([NotNull] CPrepParser.GenericAssociationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.genericAssociation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGenericAssociation([NotNull] CPrepParser.GenericAssociationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.postfixExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPostfixExpression([NotNull] CPrepParser.PostfixExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.postfixExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPostfixExpression([NotNull] CPrepParser.PostfixExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.argumentExpressionList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgumentExpressionList([NotNull] CPrepParser.ArgumentExpressionListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.argumentExpressionList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgumentExpressionList([NotNull] CPrepParser.ArgumentExpressionListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.unaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnaryExpression([NotNull] CPrepParser.UnaryExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.unaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnaryExpression([NotNull] CPrepParser.UnaryExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.unaryOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnaryOperator([NotNull] CPrepParser.UnaryOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.unaryOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnaryOperator([NotNull] CPrepParser.UnaryOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.castExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCastExpression([NotNull] CPrepParser.CastExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.castExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCastExpression([NotNull] CPrepParser.CastExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.multiplicativeExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultiplicativeExpression([NotNull] CPrepParser.MultiplicativeExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.multiplicativeExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultiplicativeExpression([NotNull] CPrepParser.MultiplicativeExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.additiveExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAdditiveExpression([NotNull] CPrepParser.AdditiveExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.additiveExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAdditiveExpression([NotNull] CPrepParser.AdditiveExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.shiftExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterShiftExpression([NotNull] CPrepParser.ShiftExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.shiftExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitShiftExpression([NotNull] CPrepParser.ShiftExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.relationalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelationalExpression([NotNull] CPrepParser.RelationalExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.relationalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelationalExpression([NotNull] CPrepParser.RelationalExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.equalityExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEqualityExpression([NotNull] CPrepParser.EqualityExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.equalityExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEqualityExpression([NotNull] CPrepParser.EqualityExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.andExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAndExpression([NotNull] CPrepParser.AndExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.andExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAndExpression([NotNull] CPrepParser.AndExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.exclusiveOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExclusiveOrExpression([NotNull] CPrepParser.ExclusiveOrExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.exclusiveOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExclusiveOrExpression([NotNull] CPrepParser.ExclusiveOrExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.inclusiveOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInclusiveOrExpression([NotNull] CPrepParser.InclusiveOrExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.inclusiveOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInclusiveOrExpression([NotNull] CPrepParser.InclusiveOrExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.logicalAndExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogicalAndExpression([NotNull] CPrepParser.LogicalAndExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.logicalAndExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogicalAndExpression([NotNull] CPrepParser.LogicalAndExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.logicalOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogicalOrExpression([NotNull] CPrepParser.LogicalOrExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.logicalOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogicalOrExpression([NotNull] CPrepParser.LogicalOrExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.conditionalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConditionalExpression([NotNull] CPrepParser.ConditionalExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.conditionalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConditionalExpression([NotNull] CPrepParser.ConditionalExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.assignmentExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignmentExpression([NotNull] CPrepParser.AssignmentExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.assignmentExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignmentExpression([NotNull] CPrepParser.AssignmentExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.assignmentOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignmentOperator([NotNull] CPrepParser.AssignmentOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.assignmentOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignmentOperator([NotNull] CPrepParser.AssignmentOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] CPrepParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] CPrepParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.constantExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstantExpression([NotNull] CPrepParser.ConstantExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.constantExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstantExpression([NotNull] CPrepParser.ConstantExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclaration([NotNull] CPrepParser.DeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclaration([NotNull] CPrepParser.DeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.declarationSpecifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclarationSpecifiers([NotNull] CPrepParser.DeclarationSpecifiersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.declarationSpecifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclarationSpecifiers([NotNull] CPrepParser.DeclarationSpecifiersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.declarationSpecifiers2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclarationSpecifiers2([NotNull] CPrepParser.DeclarationSpecifiers2Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.declarationSpecifiers2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclarationSpecifiers2([NotNull] CPrepParser.DeclarationSpecifiers2Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.declarationSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclarationSpecifier([NotNull] CPrepParser.DeclarationSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.declarationSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclarationSpecifier([NotNull] CPrepParser.DeclarationSpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.initDeclaratorList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInitDeclaratorList([NotNull] CPrepParser.InitDeclaratorListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.initDeclaratorList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInitDeclaratorList([NotNull] CPrepParser.InitDeclaratorListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.initDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInitDeclarator([NotNull] CPrepParser.InitDeclaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.initDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInitDeclarator([NotNull] CPrepParser.InitDeclaratorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.storageClassSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStorageClassSpecifier([NotNull] CPrepParser.StorageClassSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.storageClassSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStorageClassSpecifier([NotNull] CPrepParser.StorageClassSpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.typeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeSpecifier([NotNull] CPrepParser.TypeSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.typeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeSpecifier([NotNull] CPrepParser.TypeSpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.structOrUnionSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStructOrUnionSpecifier([NotNull] CPrepParser.StructOrUnionSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.structOrUnionSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStructOrUnionSpecifier([NotNull] CPrepParser.StructOrUnionSpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.structOrUnion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStructOrUnion([NotNull] CPrepParser.StructOrUnionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.structOrUnion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStructOrUnion([NotNull] CPrepParser.StructOrUnionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.structDeclarationList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStructDeclarationList([NotNull] CPrepParser.StructDeclarationListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.structDeclarationList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStructDeclarationList([NotNull] CPrepParser.StructDeclarationListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.structDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStructDeclaration([NotNull] CPrepParser.StructDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.structDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStructDeclaration([NotNull] CPrepParser.StructDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.specifierQualifierList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSpecifierQualifierList([NotNull] CPrepParser.SpecifierQualifierListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.specifierQualifierList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSpecifierQualifierList([NotNull] CPrepParser.SpecifierQualifierListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.structDeclaratorList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStructDeclaratorList([NotNull] CPrepParser.StructDeclaratorListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.structDeclaratorList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStructDeclaratorList([NotNull] CPrepParser.StructDeclaratorListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.structDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStructDeclarator([NotNull] CPrepParser.StructDeclaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.structDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStructDeclarator([NotNull] CPrepParser.StructDeclaratorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.enumSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumSpecifier([NotNull] CPrepParser.EnumSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.enumSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumSpecifier([NotNull] CPrepParser.EnumSpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.enumeratorList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumeratorList([NotNull] CPrepParser.EnumeratorListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.enumeratorList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumeratorList([NotNull] CPrepParser.EnumeratorListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.enumerator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumerator([NotNull] CPrepParser.EnumeratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.enumerator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumerator([NotNull] CPrepParser.EnumeratorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.enumerationConstant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumerationConstant([NotNull] CPrepParser.EnumerationConstantContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.enumerationConstant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumerationConstant([NotNull] CPrepParser.EnumerationConstantContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.atomicTypeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAtomicTypeSpecifier([NotNull] CPrepParser.AtomicTypeSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.atomicTypeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAtomicTypeSpecifier([NotNull] CPrepParser.AtomicTypeSpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.typeQualifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeQualifier([NotNull] CPrepParser.TypeQualifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.typeQualifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeQualifier([NotNull] CPrepParser.TypeQualifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.functionSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionSpecifier([NotNull] CPrepParser.FunctionSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.functionSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionSpecifier([NotNull] CPrepParser.FunctionSpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.alignmentSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAlignmentSpecifier([NotNull] CPrepParser.AlignmentSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.alignmentSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAlignmentSpecifier([NotNull] CPrepParser.AlignmentSpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.declarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclarator([NotNull] CPrepParser.DeclaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.declarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclarator([NotNull] CPrepParser.DeclaratorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.directDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDirectDeclarator([NotNull] CPrepParser.DirectDeclaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.directDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDirectDeclarator([NotNull] CPrepParser.DirectDeclaratorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.gccDeclaratorExtension"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGccDeclaratorExtension([NotNull] CPrepParser.GccDeclaratorExtensionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.gccDeclaratorExtension"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGccDeclaratorExtension([NotNull] CPrepParser.GccDeclaratorExtensionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.gccAttributeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGccAttributeSpecifier([NotNull] CPrepParser.GccAttributeSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.gccAttributeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGccAttributeSpecifier([NotNull] CPrepParser.GccAttributeSpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.gccAttributeList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGccAttributeList([NotNull] CPrepParser.GccAttributeListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.gccAttributeList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGccAttributeList([NotNull] CPrepParser.GccAttributeListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.gccAttribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGccAttribute([NotNull] CPrepParser.GccAttributeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.gccAttribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGccAttribute([NotNull] CPrepParser.GccAttributeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.nestedParenthesesBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNestedParenthesesBlock([NotNull] CPrepParser.NestedParenthesesBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.nestedParenthesesBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNestedParenthesesBlock([NotNull] CPrepParser.NestedParenthesesBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.pointer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPointer([NotNull] CPrepParser.PointerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.pointer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPointer([NotNull] CPrepParser.PointerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.typeQualifierList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeQualifierList([NotNull] CPrepParser.TypeQualifierListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.typeQualifierList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeQualifierList([NotNull] CPrepParser.TypeQualifierListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.parameterTypeList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameterTypeList([NotNull] CPrepParser.ParameterTypeListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.parameterTypeList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameterTypeList([NotNull] CPrepParser.ParameterTypeListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.parameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameterList([NotNull] CPrepParser.ParameterListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.parameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameterList([NotNull] CPrepParser.ParameterListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.parameterDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameterDeclaration([NotNull] CPrepParser.ParameterDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.parameterDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameterDeclaration([NotNull] CPrepParser.ParameterDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.identifierList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdentifierList([NotNull] CPrepParser.IdentifierListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.identifierList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdentifierList([NotNull] CPrepParser.IdentifierListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.typeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeName([NotNull] CPrepParser.TypeNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.typeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeName([NotNull] CPrepParser.TypeNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.abstractDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAbstractDeclarator([NotNull] CPrepParser.AbstractDeclaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.abstractDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAbstractDeclarator([NotNull] CPrepParser.AbstractDeclaratorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.directAbstractDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDirectAbstractDeclarator([NotNull] CPrepParser.DirectAbstractDeclaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.directAbstractDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDirectAbstractDeclarator([NotNull] CPrepParser.DirectAbstractDeclaratorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.typedefName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypedefName([NotNull] CPrepParser.TypedefNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.typedefName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypedefName([NotNull] CPrepParser.TypedefNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInitializer([NotNull] CPrepParser.InitializerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInitializer([NotNull] CPrepParser.InitializerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.initializerList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInitializerList([NotNull] CPrepParser.InitializerListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.initializerList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInitializerList([NotNull] CPrepParser.InitializerListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.designation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDesignation([NotNull] CPrepParser.DesignationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.designation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDesignation([NotNull] CPrepParser.DesignationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.designatorList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDesignatorList([NotNull] CPrepParser.DesignatorListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.designatorList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDesignatorList([NotNull] CPrepParser.DesignatorListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.designator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDesignator([NotNull] CPrepParser.DesignatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.designator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDesignator([NotNull] CPrepParser.DesignatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.staticAssertDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStaticAssertDeclaration([NotNull] CPrepParser.StaticAssertDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.staticAssertDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStaticAssertDeclaration([NotNull] CPrepParser.StaticAssertDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] CPrepParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] CPrepParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.labeledStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLabeledStatement([NotNull] CPrepParser.LabeledStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.labeledStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLabeledStatement([NotNull] CPrepParser.LabeledStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.compoundStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompoundStatement([NotNull] CPrepParser.CompoundStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.compoundStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompoundStatement([NotNull] CPrepParser.CompoundStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.blockItemList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlockItemList([NotNull] CPrepParser.BlockItemListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.blockItemList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlockItemList([NotNull] CPrepParser.BlockItemListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.blockItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlockItem([NotNull] CPrepParser.BlockItemContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.blockItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlockItem([NotNull] CPrepParser.BlockItemContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.expressionStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpressionStatement([NotNull] CPrepParser.ExpressionStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.expressionStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpressionStatement([NotNull] CPrepParser.ExpressionStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.selectionStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSelectionStatement([NotNull] CPrepParser.SelectionStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.selectionStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSelectionStatement([NotNull] CPrepParser.SelectionStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.iterationStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIterationStatement([NotNull] CPrepParser.IterationStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.iterationStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIterationStatement([NotNull] CPrepParser.IterationStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.forCondition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForCondition([NotNull] CPrepParser.ForConditionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.forCondition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForCondition([NotNull] CPrepParser.ForConditionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.forDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForDeclaration([NotNull] CPrepParser.ForDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.forDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForDeclaration([NotNull] CPrepParser.ForDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.forExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForExpression([NotNull] CPrepParser.ForExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.forExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForExpression([NotNull] CPrepParser.ForExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.jumpStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJumpStatement([NotNull] CPrepParser.JumpStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.jumpStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJumpStatement([NotNull] CPrepParser.JumpStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.compilationUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompilationUnit([NotNull] CPrepParser.CompilationUnitContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.compilationUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompilationUnit([NotNull] CPrepParser.CompilationUnitContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.translationUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTranslationUnit([NotNull] CPrepParser.TranslationUnitContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.translationUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTranslationUnit([NotNull] CPrepParser.TranslationUnitContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.externalDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExternalDeclaration([NotNull] CPrepParser.ExternalDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.externalDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExternalDeclaration([NotNull] CPrepParser.ExternalDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.functionDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionDefinition([NotNull] CPrepParser.FunctionDefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.functionDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionDefinition([NotNull] CPrepParser.FunctionDefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.declarationList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclarationList([NotNull] CPrepParser.DeclarationListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.declarationList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclarationList([NotNull] CPrepParser.DeclarationListContext context);
}
} // namespace QMKLib.Layout.CPrep
