//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from grammar/CPrep.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace QMKLib.Layout.CPrep {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ICPrepListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class CPrepBaseListener : ICPrepListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.defineOrEnd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDefineOrEnd([NotNull] CPrepParser.DefineOrEndContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.defineOrEnd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDefineOrEnd([NotNull] CPrepParser.DefineOrEndContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.end"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnd([NotNull] CPrepParser.EndContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.end"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnd([NotNull] CPrepParser.EndContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.defineDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDefineDeclaration([NotNull] CPrepParser.DefineDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.defineDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDefineDeclaration([NotNull] CPrepParser.DefineDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.defineSubst"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDefineSubst([NotNull] CPrepParser.DefineSubstContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.defineSubst"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDefineSubst([NotNull] CPrepParser.DefineSubstContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.layoutMacro"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLayoutMacro([NotNull] CPrepParser.LayoutMacroContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.layoutMacro"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLayoutMacro([NotNull] CPrepParser.LayoutMacroContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.layoutTargetRow"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLayoutTargetRow([NotNull] CPrepParser.LayoutTargetRowContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.layoutTargetRow"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLayoutTargetRow([NotNull] CPrepParser.LayoutTargetRowContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.layoutTarget"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLayoutTarget([NotNull] CPrepParser.LayoutTargetContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.layoutTarget"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLayoutTarget([NotNull] CPrepParser.LayoutTargetContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.layoutSource"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLayoutSource([NotNull] CPrepParser.LayoutSourceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.layoutSource"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLayoutSource([NotNull] CPrepParser.LayoutSourceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.primaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimaryExpression([NotNull] CPrepParser.PrimaryExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.primaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimaryExpression([NotNull] CPrepParser.PrimaryExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.genericSelection"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGenericSelection([NotNull] CPrepParser.GenericSelectionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.genericSelection"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGenericSelection([NotNull] CPrepParser.GenericSelectionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.genericAssocList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGenericAssocList([NotNull] CPrepParser.GenericAssocListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.genericAssocList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGenericAssocList([NotNull] CPrepParser.GenericAssocListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.genericAssociation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGenericAssociation([NotNull] CPrepParser.GenericAssociationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.genericAssociation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGenericAssociation([NotNull] CPrepParser.GenericAssociationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.postfixExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPostfixExpression([NotNull] CPrepParser.PostfixExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.postfixExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPostfixExpression([NotNull] CPrepParser.PostfixExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.argumentExpressionList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgumentExpressionList([NotNull] CPrepParser.ArgumentExpressionListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.argumentExpressionList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgumentExpressionList([NotNull] CPrepParser.ArgumentExpressionListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.unaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnaryExpression([NotNull] CPrepParser.UnaryExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.unaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnaryExpression([NotNull] CPrepParser.UnaryExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.unaryOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnaryOperator([NotNull] CPrepParser.UnaryOperatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.unaryOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnaryOperator([NotNull] CPrepParser.UnaryOperatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.castExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCastExpression([NotNull] CPrepParser.CastExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.castExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCastExpression([NotNull] CPrepParser.CastExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.multiplicativeExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMultiplicativeExpression([NotNull] CPrepParser.MultiplicativeExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.multiplicativeExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMultiplicativeExpression([NotNull] CPrepParser.MultiplicativeExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.additiveExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAdditiveExpression([NotNull] CPrepParser.AdditiveExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.additiveExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAdditiveExpression([NotNull] CPrepParser.AdditiveExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.shiftExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterShiftExpression([NotNull] CPrepParser.ShiftExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.shiftExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitShiftExpression([NotNull] CPrepParser.ShiftExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.relationalExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRelationalExpression([NotNull] CPrepParser.RelationalExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.relationalExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRelationalExpression([NotNull] CPrepParser.RelationalExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.equalityExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEqualityExpression([NotNull] CPrepParser.EqualityExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.equalityExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEqualityExpression([NotNull] CPrepParser.EqualityExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.andExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAndExpression([NotNull] CPrepParser.AndExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.andExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAndExpression([NotNull] CPrepParser.AndExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.exclusiveOrExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExclusiveOrExpression([NotNull] CPrepParser.ExclusiveOrExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.exclusiveOrExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExclusiveOrExpression([NotNull] CPrepParser.ExclusiveOrExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.inclusiveOrExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInclusiveOrExpression([NotNull] CPrepParser.InclusiveOrExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.inclusiveOrExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInclusiveOrExpression([NotNull] CPrepParser.InclusiveOrExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.logicalAndExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogicalAndExpression([NotNull] CPrepParser.LogicalAndExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.logicalAndExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogicalAndExpression([NotNull] CPrepParser.LogicalAndExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.logicalOrExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogicalOrExpression([NotNull] CPrepParser.LogicalOrExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.logicalOrExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogicalOrExpression([NotNull] CPrepParser.LogicalOrExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.conditionalExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConditionalExpression([NotNull] CPrepParser.ConditionalExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.conditionalExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConditionalExpression([NotNull] CPrepParser.ConditionalExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.assignmentExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignmentExpression([NotNull] CPrepParser.AssignmentExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.assignmentExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignmentExpression([NotNull] CPrepParser.AssignmentExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.assignmentOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignmentOperator([NotNull] CPrepParser.AssignmentOperatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.assignmentOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignmentOperator([NotNull] CPrepParser.AssignmentOperatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] CPrepParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] CPrepParser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.constantExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstantExpression([NotNull] CPrepParser.ConstantExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.constantExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstantExpression([NotNull] CPrepParser.ConstantExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclaration([NotNull] CPrepParser.DeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclaration([NotNull] CPrepParser.DeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.declarationSpecifiers"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclarationSpecifiers([NotNull] CPrepParser.DeclarationSpecifiersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.declarationSpecifiers"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclarationSpecifiers([NotNull] CPrepParser.DeclarationSpecifiersContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.declarationSpecifiers2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclarationSpecifiers2([NotNull] CPrepParser.DeclarationSpecifiers2Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.declarationSpecifiers2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclarationSpecifiers2([NotNull] CPrepParser.DeclarationSpecifiers2Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.declarationSpecifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclarationSpecifier([NotNull] CPrepParser.DeclarationSpecifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.declarationSpecifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclarationSpecifier([NotNull] CPrepParser.DeclarationSpecifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.initDeclaratorList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInitDeclaratorList([NotNull] CPrepParser.InitDeclaratorListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.initDeclaratorList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInitDeclaratorList([NotNull] CPrepParser.InitDeclaratorListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.initDeclarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInitDeclarator([NotNull] CPrepParser.InitDeclaratorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.initDeclarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInitDeclarator([NotNull] CPrepParser.InitDeclaratorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.storageClassSpecifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStorageClassSpecifier([NotNull] CPrepParser.StorageClassSpecifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.storageClassSpecifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStorageClassSpecifier([NotNull] CPrepParser.StorageClassSpecifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.typeSpecifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeSpecifier([NotNull] CPrepParser.TypeSpecifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.typeSpecifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeSpecifier([NotNull] CPrepParser.TypeSpecifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.structOrUnionSpecifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStructOrUnionSpecifier([NotNull] CPrepParser.StructOrUnionSpecifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.structOrUnionSpecifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStructOrUnionSpecifier([NotNull] CPrepParser.StructOrUnionSpecifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.structOrUnion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStructOrUnion([NotNull] CPrepParser.StructOrUnionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.structOrUnion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStructOrUnion([NotNull] CPrepParser.StructOrUnionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.structDeclarationList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStructDeclarationList([NotNull] CPrepParser.StructDeclarationListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.structDeclarationList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStructDeclarationList([NotNull] CPrepParser.StructDeclarationListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.structDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStructDeclaration([NotNull] CPrepParser.StructDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.structDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStructDeclaration([NotNull] CPrepParser.StructDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.specifierQualifierList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSpecifierQualifierList([NotNull] CPrepParser.SpecifierQualifierListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.specifierQualifierList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSpecifierQualifierList([NotNull] CPrepParser.SpecifierQualifierListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.structDeclaratorList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStructDeclaratorList([NotNull] CPrepParser.StructDeclaratorListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.structDeclaratorList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStructDeclaratorList([NotNull] CPrepParser.StructDeclaratorListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.structDeclarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStructDeclarator([NotNull] CPrepParser.StructDeclaratorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.structDeclarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStructDeclarator([NotNull] CPrepParser.StructDeclaratorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.enumSpecifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumSpecifier([NotNull] CPrepParser.EnumSpecifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.enumSpecifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumSpecifier([NotNull] CPrepParser.EnumSpecifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.enumeratorList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumeratorList([NotNull] CPrepParser.EnumeratorListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.enumeratorList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumeratorList([NotNull] CPrepParser.EnumeratorListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.enumerator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumerator([NotNull] CPrepParser.EnumeratorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.enumerator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumerator([NotNull] CPrepParser.EnumeratorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.enumerationConstant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumerationConstant([NotNull] CPrepParser.EnumerationConstantContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.enumerationConstant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumerationConstant([NotNull] CPrepParser.EnumerationConstantContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.atomicTypeSpecifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAtomicTypeSpecifier([NotNull] CPrepParser.AtomicTypeSpecifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.atomicTypeSpecifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAtomicTypeSpecifier([NotNull] CPrepParser.AtomicTypeSpecifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.typeQualifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeQualifier([NotNull] CPrepParser.TypeQualifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.typeQualifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeQualifier([NotNull] CPrepParser.TypeQualifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.functionSpecifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionSpecifier([NotNull] CPrepParser.FunctionSpecifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.functionSpecifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionSpecifier([NotNull] CPrepParser.FunctionSpecifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.alignmentSpecifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAlignmentSpecifier([NotNull] CPrepParser.AlignmentSpecifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.alignmentSpecifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAlignmentSpecifier([NotNull] CPrepParser.AlignmentSpecifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.declarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclarator([NotNull] CPrepParser.DeclaratorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.declarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclarator([NotNull] CPrepParser.DeclaratorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.directDeclarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDirectDeclarator([NotNull] CPrepParser.DirectDeclaratorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.directDeclarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDirectDeclarator([NotNull] CPrepParser.DirectDeclaratorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.gccDeclaratorExtension"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGccDeclaratorExtension([NotNull] CPrepParser.GccDeclaratorExtensionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.gccDeclaratorExtension"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGccDeclaratorExtension([NotNull] CPrepParser.GccDeclaratorExtensionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.gccAttributeSpecifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGccAttributeSpecifier([NotNull] CPrepParser.GccAttributeSpecifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.gccAttributeSpecifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGccAttributeSpecifier([NotNull] CPrepParser.GccAttributeSpecifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.gccAttributeList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGccAttributeList([NotNull] CPrepParser.GccAttributeListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.gccAttributeList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGccAttributeList([NotNull] CPrepParser.GccAttributeListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.gccAttribute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGccAttribute([NotNull] CPrepParser.GccAttributeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.gccAttribute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGccAttribute([NotNull] CPrepParser.GccAttributeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.nestedParenthesesBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNestedParenthesesBlock([NotNull] CPrepParser.NestedParenthesesBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.nestedParenthesesBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNestedParenthesesBlock([NotNull] CPrepParser.NestedParenthesesBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.pointer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPointer([NotNull] CPrepParser.PointerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.pointer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPointer([NotNull] CPrepParser.PointerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.typeQualifierList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeQualifierList([NotNull] CPrepParser.TypeQualifierListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.typeQualifierList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeQualifierList([NotNull] CPrepParser.TypeQualifierListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.parameterTypeList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameterTypeList([NotNull] CPrepParser.ParameterTypeListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.parameterTypeList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameterTypeList([NotNull] CPrepParser.ParameterTypeListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.parameterList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameterList([NotNull] CPrepParser.ParameterListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.parameterList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameterList([NotNull] CPrepParser.ParameterListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.parameterDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameterDeclaration([NotNull] CPrepParser.ParameterDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.parameterDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameterDeclaration([NotNull] CPrepParser.ParameterDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.identifierList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdentifierList([NotNull] CPrepParser.IdentifierListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.identifierList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdentifierList([NotNull] CPrepParser.IdentifierListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.typeName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeName([NotNull] CPrepParser.TypeNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.typeName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeName([NotNull] CPrepParser.TypeNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.abstractDeclarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAbstractDeclarator([NotNull] CPrepParser.AbstractDeclaratorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.abstractDeclarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAbstractDeclarator([NotNull] CPrepParser.AbstractDeclaratorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.directAbstractDeclarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDirectAbstractDeclarator([NotNull] CPrepParser.DirectAbstractDeclaratorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.directAbstractDeclarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDirectAbstractDeclarator([NotNull] CPrepParser.DirectAbstractDeclaratorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.typedefName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypedefName([NotNull] CPrepParser.TypedefNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.typedefName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypedefName([NotNull] CPrepParser.TypedefNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.initializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInitializer([NotNull] CPrepParser.InitializerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.initializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInitializer([NotNull] CPrepParser.InitializerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.initializerList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInitializerList([NotNull] CPrepParser.InitializerListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.initializerList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInitializerList([NotNull] CPrepParser.InitializerListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.designation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDesignation([NotNull] CPrepParser.DesignationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.designation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDesignation([NotNull] CPrepParser.DesignationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.designatorList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDesignatorList([NotNull] CPrepParser.DesignatorListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.designatorList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDesignatorList([NotNull] CPrepParser.DesignatorListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.designator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDesignator([NotNull] CPrepParser.DesignatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.designator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDesignator([NotNull] CPrepParser.DesignatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.staticAssertDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStaticAssertDeclaration([NotNull] CPrepParser.StaticAssertDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.staticAssertDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStaticAssertDeclaration([NotNull] CPrepParser.StaticAssertDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] CPrepParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] CPrepParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.labeledStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLabeledStatement([NotNull] CPrepParser.LabeledStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.labeledStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLabeledStatement([NotNull] CPrepParser.LabeledStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.compoundStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCompoundStatement([NotNull] CPrepParser.CompoundStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.compoundStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCompoundStatement([NotNull] CPrepParser.CompoundStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.blockItemList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlockItemList([NotNull] CPrepParser.BlockItemListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.blockItemList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlockItemList([NotNull] CPrepParser.BlockItemListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.blockItem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlockItem([NotNull] CPrepParser.BlockItemContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.blockItem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlockItem([NotNull] CPrepParser.BlockItemContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.expressionStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpressionStatement([NotNull] CPrepParser.ExpressionStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.expressionStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpressionStatement([NotNull] CPrepParser.ExpressionStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.selectionStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSelectionStatement([NotNull] CPrepParser.SelectionStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.selectionStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSelectionStatement([NotNull] CPrepParser.SelectionStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.iterationStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIterationStatement([NotNull] CPrepParser.IterationStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.iterationStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIterationStatement([NotNull] CPrepParser.IterationStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.forCondition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForCondition([NotNull] CPrepParser.ForConditionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.forCondition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForCondition([NotNull] CPrepParser.ForConditionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.forDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForDeclaration([NotNull] CPrepParser.ForDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.forDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForDeclaration([NotNull] CPrepParser.ForDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.forExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForExpression([NotNull] CPrepParser.ForExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.forExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForExpression([NotNull] CPrepParser.ForExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.jumpStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJumpStatement([NotNull] CPrepParser.JumpStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.jumpStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJumpStatement([NotNull] CPrepParser.JumpStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.compilationUnit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCompilationUnit([NotNull] CPrepParser.CompilationUnitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.compilationUnit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCompilationUnit([NotNull] CPrepParser.CompilationUnitContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.translationUnit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTranslationUnit([NotNull] CPrepParser.TranslationUnitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.translationUnit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTranslationUnit([NotNull] CPrepParser.TranslationUnitContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.externalDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExternalDeclaration([NotNull] CPrepParser.ExternalDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.externalDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExternalDeclaration([NotNull] CPrepParser.ExternalDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.functionDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionDefinition([NotNull] CPrepParser.FunctionDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.functionDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionDefinition([NotNull] CPrepParser.FunctionDefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPrepParser.declarationList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclarationList([NotNull] CPrepParser.DeclarationListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPrepParser.declarationList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclarationList([NotNull] CPrepParser.DeclarationListContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace QMKLib.Layout.CPrep
